incSR_WZ_1
incSR_WZ_2
incSR_WZ_3
Traceback (most recent call last):
  File "/home/tombs/Documents/interval-evidence/searches/atlas_susy_3L_2021/dump_fits.py", line 79, in <module>
    main()
  File "/home/tombs/Documents/interval-evidence/searches/atlas_susy_3L_2021/dump_fits.py", line 49, in main
    dump(name, lo, hi, region_name_to_anchors=region_name_to_anchors)
  File "/home/tombs/Documents/interval-evidence/searches/atlas_susy_3L_2021/dump_fits.py", line 69, in dump
    fit_linspace.fit(
  File "/home/tombs/Documents/interval-evidence/discohisto/fit_linspace.py", line 40, in fit
    raise RuntimeError(yield_)
RuntimeError: 0.0

real	1m12.481s
user	1m15.054s
sys	0m3.683s
